//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/nukleros/operator-builder-tools/pkg/status"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSPodIdentityWebhook) DeepCopyInto(out *AWSPodIdentityWebhook) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSPodIdentityWebhook.
func (in *AWSPodIdentityWebhook) DeepCopy() *AWSPodIdentityWebhook {
	if in == nil {
		return nil
	}
	out := new(AWSPodIdentityWebhook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSPodIdentityWebhook) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSPodIdentityWebhookList) DeepCopyInto(out *AWSPodIdentityWebhookList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSPodIdentityWebhook, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSPodIdentityWebhookList.
func (in *AWSPodIdentityWebhookList) DeepCopy() *AWSPodIdentityWebhookList {
	if in == nil {
		return nil
	}
	out := new(AWSPodIdentityWebhookList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSPodIdentityWebhookList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSPodIdentityWebhookSpec) DeepCopyInto(out *AWSPodIdentityWebhookSpec) {
	*out = *in
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSPodIdentityWebhookSpec.
func (in *AWSPodIdentityWebhookSpec) DeepCopy() *AWSPodIdentityWebhookSpec {
	if in == nil {
		return nil
	}
	out := new(AWSPodIdentityWebhookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSPodIdentityWebhookSpecResources) DeepCopyInto(out *AWSPodIdentityWebhookSpecResources) {
	*out = *in
	out.Requests = in.Requests
	out.Limits = in.Limits
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSPodIdentityWebhookSpecResources.
func (in *AWSPodIdentityWebhookSpecResources) DeepCopy() *AWSPodIdentityWebhookSpecResources {
	if in == nil {
		return nil
	}
	out := new(AWSPodIdentityWebhookSpecResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSPodIdentityWebhookSpecResourcesLimits) DeepCopyInto(out *AWSPodIdentityWebhookSpecResourcesLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSPodIdentityWebhookSpecResourcesLimits.
func (in *AWSPodIdentityWebhookSpecResourcesLimits) DeepCopy() *AWSPodIdentityWebhookSpecResourcesLimits {
	if in == nil {
		return nil
	}
	out := new(AWSPodIdentityWebhookSpecResourcesLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSPodIdentityWebhookSpecResourcesRequests) DeepCopyInto(out *AWSPodIdentityWebhookSpecResourcesRequests) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSPodIdentityWebhookSpecResourcesRequests.
func (in *AWSPodIdentityWebhookSpecResourcesRequests) DeepCopy() *AWSPodIdentityWebhookSpecResourcesRequests {
	if in == nil {
		return nil
	}
	out := new(AWSPodIdentityWebhookSpecResourcesRequests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSPodIdentityWebhookStatus) DeepCopyInto(out *AWSPodIdentityWebhookStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*status.PhaseCondition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(status.PhaseCondition)
				**out = **in
			}
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]*status.ChildResource, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(status.ChildResource)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSPodIdentityWebhookStatus.
func (in *AWSPodIdentityWebhookStatus) DeepCopy() *AWSPodIdentityWebhookStatus {
	if in == nil {
		return nil
	}
	out := new(AWSPodIdentityWebhookStatus)
	in.DeepCopyInto(out)
	return out
}
