---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-pod-identity-webhook
  namespace: tbd-identity-system # +operator-builder:field:name=namespace,default="tbd-identity-system",type=string
  labels:
    app: aws-pod-identity-webhook
    app.kubernetes.io/name: aws-pod-identity-webhook
    app.kubernetes.io/instance: aws-pod-identity-webhook
    app.kubernetes.io/component: aws-pod-identity-webhook
    capabilities.tbd.io/capability: identity
    capabilities.tbd.io/version: v0.0.1
    capabilities.tbd.io/platform-version: unstable
    app.kubernetes.io/version: v0.5.3
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: identity-operator
spec:
  # +operator-builder:field:name=replicas,default="2",type=int,description=`
  # Number of replicas to use for the AWS pod identity webhook deployment.`
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: aws-pod-identity-webhook
      app.kubernetes.io/instance: aws-pod-identity-webhook
      app.kubernetes.io/component: aws-pod-identity-webhook
  template:
    metadata:
      labels:
        app: aws-pod-identity-webhook
        app.kubernetes.io/component: aws-pod-identity-webhook
        app.kubernetes.io/name: aws-pod-identity-webhook
        app.kubernetes.io/instance: aws-pod-identity-webhook
        capabilities.tbd.io/capability: identity
        capabilities.tbd.io/version: v0.0.1
        capabilities.tbd.io/platform-version: unstable
        app.kubernetes.io/version: v0.5.3
        app.kubernetes.io/part-of: platform
        app.kubernetes.io/managed-by: identity-operator
    spec:
      serviceAccountName: aws-pod-identity-webhook
      containers:
        - name: aws-pod-identity-webhook
          # +operator-builder:field:name=image,default="amazon/amazon-eks-pod-identity-webhook:v0.5.3",type=string,description=`
          # Image to use for AWS pod identity webhook deployment.`
          image: amazon/amazon-eks-pod-identity-webhook:v0.5.3
          imagePullPolicy: Always
          command:
            - /webhook
            - --in-cluster=false
            - --namespace=tbd-identity-system # +operator-builder:field:name=namespace,replace=tbd-identity-system,default="tbd-identity-system",type=string
            - --service-name=aws-pod-identity-webhook
            - --annotation-prefix=eks.amazonaws.com
            - --token-audience=kubernetes.default.svc
            - --logtostderr
            - --port=9443
          volumeMounts:
            - name: cert
              mountPath: /etc/webhook/certs
              readOnly: true
          resources:
            requests:
              # +operator-builder:field:name=resources.requests.cpu,default="25m",type=string,description=`
              # CPU requests to use for AWS pod identity webhook deployment.`
              cpu: 25m
              # +operator-builder:field:name=resources.requests.memory,default="32Mi",type=string,description=`
              # Memory requests to use for AWS pod identity webhook deployment.`
              memory: 32Mi
            limits:
              # +operator-builder:field:name=resources.limits.memory,default="64Mi",type=string,description=`
              # Memory limits to use for AWS pod identity webhook deployment.`
              memory: 64Mi
      volumes:
        - name: cert
          secret:
            secretName: aws-pod-identity-webhook-cert
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - aws-pod-identity-webhook
      nodeSelector:
        kubernetes.io/os: linux
        tbd.io/node-type: platform
        kubernetes.io/arch: arm64
