---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-pod-identity-webhook
  namespace: tbd-identity-system # +operator-builder:field:name=namespace,default="tbd-identity-system",type=string
  labels:
    app: aws-pod-identity-webhook
    app.kubernetes.io/name: aws-pod-identity-webhook
    app.kubernetes.io/instance: aws-pod-identity-webhook
    app.kubernetes.io/component: aws-pod-identity-webhook
    capabilities.tbd.io/capability: identity
    capabilities.tbd.io/version: v0.0.1
    capabilities.tbd.io/platform-version: unstable
    app.kubernetes.io/version: v0.5.3
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: identity-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aws-pod-identity-webhook
  namespace: tbd-identity-system # +operator-builder:field:name=namespace,default="tbd-identity-system",type=string
  labels:
    app: aws-pod-identity-webhook
    app.kubernetes.io/name: aws-pod-identity-webhook
    app.kubernetes.io/instance: aws-pod-identity-webhook
    app.kubernetes.io/component: aws-pod-identity-webhook
    capabilities.tbd.io/capability: identity
    capabilities.tbd.io/version: v0.0.1
    capabilities.tbd.io/platform-version: unstable
    app.kubernetes.io/version: v0.5.3
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: identity-operator
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - update
      - patch
    resourceNames:
      - pod-identity-webhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aws-pod-identity-webhook
  namespace: tbd-identity-system # +operator-builder:field:name=namespace,default="tbd-identity-system",type=string
  labels:
    app: aws-pod-identity-webhook
    app.kubernetes.io/name: aws-pod-identity-webhook
    app.kubernetes.io/instance: aws-pod-identity-webhook
    app.kubernetes.io/component: aws-pod-identity-webhook
    capabilities.tbd.io/capability: identity
    capabilities.tbd.io/version: v0.0.1
    capabilities.tbd.io/platform-version: unstable
    app.kubernetes.io/version: v0.5.3
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: identity-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aws-pod-identity-webhook
subjects:
  - kind: ServiceAccount
    name: aws-pod-identity-webhook
    namespace: tbd-identity-system # +operator-builder:field:name=namespace,default="tbd-identity-system",type=string
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-pod-identity-webhook
  labels:
    app: aws-pod-identity-webhook
    app.kubernetes.io/name: aws-pod-identity-webhook
    app.kubernetes.io/instance: aws-pod-identity-webhook
    app.kubernetes.io/component: aws-pod-identity-webhook
    capabilities.tbd.io/capability: identity
    capabilities.tbd.io/version: v0.0.1
    capabilities.tbd.io/platform-version: unstable
    app.kubernetes.io/version: v0.5.3
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: identity-operator
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
    verbs:
      - create
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-pod-identity-webhook
  labels:
    app: aws-pod-identity-webhook
    app.kubernetes.io/name: aws-pod-identity-webhook
    app.kubernetes.io/instance: aws-pod-identity-webhook
    app.kubernetes.io/component: aws-pod-identity-webhook
    capabilities.tbd.io/capability: identity
    capabilities.tbd.io/version: v0.0.1
    capabilities.tbd.io/platform-version: unstable
    app.kubernetes.io/version: v0.5.3
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: identity-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-pod-identity-webhook
subjects:
  - kind: ServiceAccount
    name: aws-pod-identity-webhook
    namespace: tbd-identity-system # +operator-builder:field:name=namespace,default="tbd-identity-system",type=string
