# permissions for end users to view awspodidentitywebhooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: awspodidentitywebhook-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: capabilities-identity-operator
    app.kubernetes.io/part-of: capabilities-identity-operator
    app.kubernetes.io/managed-by: kustomize
  name: awspodidentitywebhook-viewer-role
rules:
- apiGroups:
  - identity.platform.tbd.io
  resources:
  - awspodidentitywebhooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - identity.platform.tbd.io
  resources:
  - awspodidentitywebhooks/status
  verbs:
  - get
